<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIED0zZx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIED0zZx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIED0zZx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIED0zZx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIED0zZx\App_KernelDevDebugContainer([
    'container.build_hash' => 'IED0zZx',
    'container.build_id' => '496623f0',
    'container.build_time' => 1644084346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIED0zZx');
