<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIJGDPaR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIJGDPaR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIJGDPaR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIJGDPaR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIJGDPaR\App_KernelDevDebugContainer([
    'container.build_hash' => 'IJGDPaR',
    'container.build_id' => '5019b483',
    'container.build_time' => 1644094684,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIJGDPaR');
