<?php

namespace ContainerCZ4qCE9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OtTBDMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ot_tBDM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ot_tBDM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'advert' => ['privates', '.errored..service_locator.ot_tBDM.App\\Entity\\Advert', NULL, 'Cannot autowire service ".service_locator.ot_tBDM": it references class "App\\Entity\\Advert" but no such service exists.'],
        ], [
            'advert' => 'App\\Entity\\Advert',
        ]);
    }
}
