<?php

namespace Container2YR279R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdvertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ot_tBDM.App\Entity\Advert' shared service.
     *
     * @return \App\Entity\Advert
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ot_tBDM": it references class "App\\Entity\\Advert" but no such service exists.');
    }
}
