<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'js/app' => [
            'js' => [
                '/build/runtime.efa5318b.js',
                '/build/577.df108f39.js',
                '/build/js/app.0001bb8c.js',
            ],
        ],
        'css/app' => [
            'js' => [
                '/build/runtime.efa5318b.js',
            ],
            'css' => [
                '/build/css/app.f4be9bb6.css',
            ],
        ],
    ],
],

]];
